# Generated by Django 4.1.5 on 2023-01-07 16:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('text', models.CharField(max_length=255)),
                ('filters', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], default='NEW', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_client.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mailing.mailing')),
            ],
        ),
    ]
